# speaker configuration
speakers = {
    "Firefly":{
        "gpt_model" : "/root/autodl-tmp/GPT-SoVITS/models/GPT_models/Firefly/Firefly-e15.ckpt",
        "sovits_model" : "/root/autodl-tmp/GPT-SoVITS/models/VITS_models/Firefly/Firefly_e8_s504.pth",
        "ref_audio" : "/root/autodl-tmp/GPT-SoVITS/refer_audio/Firefly.wav",
        "ref_text" : "谢谢，如果没有您出手相助，我真的不知道该怎么办",
        "ref_language" : "zh",
        "target_language" : "zh",
        "speed_factor" : 1.0,
        "top_k" : int(15),
        "top_p" : float(1.0),
        "temperature" : float(1.2),
    },
    "Klee":{
        "gpt_model" : "/root/autodl-tmp/GPT-SoVITS/models/GPT_models/Klee/Klee-e15.ckpt",
        "sovits_model" : "/root/autodl-tmp/GPT-SoVITS/models/VITS_models/Klee/Klee_e8_s656.pth",
        "ref_audio" : "/root/autodl-tmp/GPT-SoVITS/refer_audio/Klee.wav",
        "ref_text" : "我听说，冒险家协会也有一套冒险的守则，是不是，应该去拜托他们",
        "ref_language" : "zh",
        "target_language" : "zh",
        "speed_factor" : 1.0,
        "top_k" : int(15),
        "top_p" : float(1.0),
        "temperature" : float(1.2)
    },
    "Ayaka":{
        "gpt_model" : "/root/autodl-tmp/GPT-SoVITS/models/GPT_models/Ayaka/Ayaka-e15.ckpt",
        "sovits_model" : "/root/autodl-tmp/GPT-SoVITS/models/VITS_models/Ayaka/Ayaka_315_e8_s576.pth",
        "ref_audio" : "/root/autodl-tmp/GPT-SoVITS/refer_audio/Ayaka.wav",
        "ref_text" : "请不要这么夸我，我只是做了任何人都会做的",
        "ref_language" : "zh",
        "target_language" : "zh",
        "speed_factor" : 1.0,
        "top_k" : int(15),
        "top_p" : float(1.0),
        "temperature" : float(1.2),
    },
    "Nahida":{
        "gpt_model" : "/root/autodl-tmp/GPT-SoVITS/models/GPT_models/Nahida/Nahida-e15.ckpt",
        "sovits_model" : "/root/autodl-tmp/GPT-SoVITS/models/VITS_models/Nahida/Nahida_e8_s1200.pth",
        "ref_audio" : "/root/autodl-tmp/GPT-SoVITS/refer_audio/Nahida.wav",
        "ref_text" : "这是只存在于理论中的举动，我甚至不确定有谁敢做这样的事。",
        "ref_language" : "zh",
        "target_language" : "zh",
        "speed_factor" : 1.0,
        "top_k" : int(15),
        "top_p" : float(1.0),
        "temperature" : float(1.2),
    },
    "Tribbie":{
        "gpt_model" : "/root/autodl-tmp/GPT-SoVITS/models/GPT_models/Tribbie/Tribbie-e15.ckpt",
        "sovits_model" : "/root/autodl-tmp/GPT-SoVITS/models/VITS_models/Tribbie/Tribbie_e8_s344.pth",
        "ref_audio" : "/root/autodl-tmp/GPT-SoVITS/refer_audio/Tribbie.wav",
        "ref_text" : "三者开辟天地，三者编制命运，三者捏塑生命，三者引渡灾",
        "ref_language" : "zh",
        "target_language" : "zh",
        "speed_factor" : 1.0,
        "top_k" : int(15),
        "top_p" : float(1.0),
        "temperature" : float(1.2),
    },
    "Yoimiya":{
        "gpt_model" : "/root/autodl-tmp/GPT-SoVITS/models/GPT_models/Yoimiya/Yoimiya-e5.ckpt",
        "sovits_model" : "/root/autodl-tmp/GPT-SoVITS/models/VITS_models/Yoimiya/Yoimiya_e8_s1024.pth",
        "ref_audio" : "/root/autodl-tmp/GPT-SoVITS/refer_audio/Yoimiya.wav",
        "ref_text" : "就让我们一鼓作气拿下比赛，就像，烟花升空那么快，咻的一下，在别人还没反应过来的时候，比赛已经结",
        "ref_language" : "zh",
        "target_language" : "zh",
        "speed_factor" : 1.0,
        "top_k" : int(15),
        "top_p" : float(1.0),
        "temperature" : float(1.2),
    },
    "Citlali":{
        "gpt_model" : "/root/autodl-tmp/GPT-SoVITS/models/GPT_models/Citlali/Citlali-e15.ckpt",
        "sovits_model" : "/root/autodl-tmp/GPT-SoVITS/models/VITS_models/Citlali/Citlali_e8_s1160.pth",
        "ref_audio" : "/root/autodl-tmp/GPT-SoVITS/refer_audio/Citlali.wav",
        "ref_text" : "就让我们一鼓作气拿下比赛，就像，烟花升空那么快，咻的一下，在别人还没反应过来的时候，比赛已经结",
        "ref_language" : "zh",
        "target_language" : "zh",
        "speed_factor" : 1.0,
        "top_k" : int(15),
        "top_p" : float(1.0),
        "temperature" : float(1.2),
    }
}